name: 'Node Dependency Check'
description: 'Scan project dependencies for vulnerabilities using dependency-check'
inputs:
  project:
    description: 'Project name'
    required: false
    default: '${{ github.event.repository.name }}'
  path:
    description: 'Path to scan'
    required: false
    default: '.'
  args:
    description: 'Extra arguments for dependency-check'
    required: false
    default: --disableCentral --failOnCVSS 7 --enableRetired --noupdate --disableNodeAudit --nodeAuditSkipDevDependencies --disableOssIndex
  version:
    description: 'Dependency-Check version to use'
    required: false
    default: '12.1.0'
  format:
    description: 'Report format(s), comma separated (e.g. HTML, XML, JSON)'
    required: false
    default: 'XML,JSON,HTML'
  out:
    description: 'Output directory for reports'
    required: false
    default: 'reports'
  workdir:
    description: 'Working directory to run the scan from'
    required: false
    default: '.'
runs:
  using: 'node20'
  main: 'dist/index.js'
